#!/bin/sh
# entrypoint.sh - start one COD1.6X server from environment variables (see README.md).
#
#   /cod1  the game, PAM, cod1plus.so (read-only, from the image)   -> fs_basepath
#   /data  this server's own writable folder (a volume per server)  -> fs_homepath
#
# Nothing here writes into /cod1: several servers share one image and never see each
# other's logs, demos or archived cvars.
set -eu

COD1_ROOT="${COD1_ROOT:-/cod1}"
DATA="${DATA:-/data}"
OPT="${OPT:-/opt/cod1}"
SERVERS="${SERVERS:-/servers}"
FS_GAME="${FS_GAME:-__rPAMv115b5}"

PORT="${PORT:-28960}"
SV_HOSTNAME="${SV_HOSTNAME:-COD1.6X LAN}"
GAMETYPE="${GAMETYPE:-sd}"
MAP="${MAP:-mp_harbor}"
MAPROTATION="${MAPROTATION:-}"
MAXCLIENTS="${MAXCLIENTS:-16}"
PASSWORD="${PASSWORD:-}"
RCON_PASSWORD="${RCON_PASSWORD:-}"
PAM_MODE="${PAM_MODE:-comp}"
SV_FPS="${SV_FPS:-40}"
DEDICATED="${DEDICATED:-1}"          # 1 = LAN (no master, no rate limit on LAN), 2 = internet
EXTRA_CFG="${EXTRA_CFG:-}"          # a file in servers/, executed last

MOD="$DATA/$FS_GAME"
mkdir -p "$MOD"

# a value goes inside "...": no quote, no line break, no ';' (a command separator)
clean() { printf '%s' "$1" | tr -d '";\r\n'; }

if [ -z "$RCON_PASSWORD" ]; then
    RCON_PASSWORD=$(tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c 12)
    echo "entrypoint: no RCON_PASSWORD set - generated one for this run: $RCON_PASSWORD"
fi
[ -n "$MAPROTATION" ] || MAPROTATION="gametype $GAMETYPE map $MAP"

cp "$OPT/defaults.cfg" "$MOD/defaults.cfg"
{
    echo "// generated by entrypoint.sh at every start - set these in docker-compose.yml"
    echo "seta sv_hostname \"$(clean "$SV_HOSTNAME")\""
    echo "seta g_gametype \"$(clean "$GAMETYPE")\""
    echo "seta sv_mapRotation \"$(clean "$MAPROTATION")\""
    echo "seta sv_maxclients \"$(clean "$MAXCLIENTS")\""
    echo "seta g_password \"$(clean "$PASSWORD")\""
    echo "seta rconPassword \"$(clean "$RCON_PASSWORD")\""
    echo "seta pam_mode \"$(clean "$PAM_MODE")\""
    echo "seta sv_fps \"$(clean "$SV_FPS")\""
} > "$MOD/server.cfg"

EXTRA_EXEC=""
if [ -n "$EXTRA_CFG" ]; then
    if [ -f "$SERVERS/$EXTRA_CFG" ]; then
        tr -d '\r' < "$SERVERS/$EXTRA_CFG" > "$MOD/extra.cfg"
        EXTRA_EXEC="+exec extra.cfg"
        echo "entrypoint: EXTRA_CFG servers/$EXTRA_CFG applied last"
    else
        echo "entrypoint: WARNING EXTRA_CFG=$EXTRA_CFG but servers/$EXTRA_CFG does not exist - ignored"
    fi
fi

# cod1plus.so reads competitive.cfg / ruleset.txt from the working directory, if present
for f in competitive.cfg ruleset.txt; do
    if [ -f "$SERVERS/$f" ]; then tr -d '\r' < "$SERVERS/$f" > "$DATA/$f"; fi
done
cd "$DATA"

echo "entrypoint: $SV_HOSTNAME - $GAMETYPE $MAP - udp $PORT - pam_mode $PAM_MODE - dedicated $DEDICATED"
exec env LD_PRELOAD="$COD1_ROOT/cod1plus.so" "$COD1_ROOT/cod_lnxded" \
    +set dedicated "$DEDICATED" \
    +set fs_basepath "$COD1_ROOT" \
    +set fs_homepath "$DATA" \
    +set fs_game "$FS_GAME" \
    +set sv_punkbuster 0 \
    +set net_ip 0.0.0.0 \
    +set net_port "$PORT" \
    +set logfile 2 \
    +set g_gametype "$GAMETYPE" \
    +exec defaults.cfg \
    +exec server.cfg \
    $EXTRA_EXEC \
    +map "$MAP"
